# Generated by Django 4.1.3 on 2022-12-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmsslider_cms_css_alter_cmsslider_cms_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmsslider',
            old_name='cms_ims',
            new_name='cms_img',
        ),
    ]
